.SILENT:

ARCHIVE = lab3b-604057669.tar.gz
SOURCE = Makefile README lab3b.py lab3b

default: 
	chmod u+x lab3b #just have to give execute permission for script

dist:
	tar -czf $(ARCHIVE) $(SOURCE)

clean:
	#nothing generated
	rm *.tar.gz
